EXPERIMENT_NAME: experiments/cst-pascal
DATA:
  DATASET: pascal
  PATH: <PATH_TO_DIR_WITH_DATASET>
TRAIN:
  SEED: 0
  EPOCHS: 80
  LEARNING_RATE: 1e-3
  DATA_LOADER:
    BATCH_SIZE: 12
    NUM_WORKERS: 4
METHOD:
  NAME: cst
  SUPPORT_DIM: 145
  BACKBONE_CHECKPOINT: <PATH_TO_DINOv2_CHECKPOINT>
