EXPERIMENT_NAME: experiments/emat-pascal
DATA:
  DATASET: pascal
  PATH: <PATH_TO_DIR_WITH_DATASET>
TRAIN:
  SEED: 0
  EPOCHS: 80
  LEARNING_RATE: 1e-3
  DATA_LOADER:
    BATCH_SIZE: 9
    NUM_WORKERS: 4
METHOD:
  NAME: emat
  SUPPORT_DIM: 401
  BACKBONE_CHECKPOINT: <PATH_TO_DINOv2_CHECKPOINT>
